/**
 * Script to generate icons for the Electron app
 * Run: node scripts/generate-icons.js
 *
 * Requires: npm install sharp
 */

const fs = require('fs')
const path = require('path')

// Check if sharp is available
let sharp
try {
  sharp = require('sharp')
} catch (e) {
  console.log('Sharp not installed. Installing...')
  const { execSync } = require('child_process')
  execSync('npm install sharp --save-dev', { stdio: 'inherit' })
  sharp = require('sharp')
}

const BUILD_DIR = path.join(__dirname, '../build')
const ICONS_DIR = path.join(BUILD_DIR, 'icons')

// Ensure directories exist
if (!fs.existsSync(BUILD_DIR)) fs.mkdirSync(BUILD_DIR, { recursive: true })
if (!fs.existsSync(ICONS_DIR)) fs.mkdirSync(ICONS_DIR, { recursive: true })

// Main app icon SVG (Luelis blue theme)
const mainIconSvg = `
<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#0064FA"/>
      <stop offset="100%" style="stop-color:#003D99"/>
    </linearGradient>
    <linearGradient id="accent" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#DCB40A"/>
      <stop offset="100%" style="stop-color:#B8960A"/>
    </linearGradient>
  </defs>
  <rect width="1024" height="1024" rx="200" fill="url(#bg)"/>
  <g transform="translate(200, 200)">
    <!-- L shape -->
    <path d="M100 100 L100 500 L400 500 L400 420 L180 420 L180 100 Z" fill="white"/>
    <!-- Accent bar -->
    <rect x="420" y="380" width="200" height="120" rx="20" fill="url(#accent)"/>
  </g>
</svg>
`

// Tray icon SVG (smaller, simpler)
const trayIconSvg = `
<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
  <rect width="32" height="32" rx="6" fill="#0064FA"/>
  <path d="M8 8 L8 24 L20 24 L20 21 L11 21 L11 8 Z" fill="white"/>
  <rect x="21" y="19" width="5" height="5" rx="1" fill="#DCB40A"/>
</svg>
`

// Notification success icon
const notificationSuccessSvg = `
<svg width="64" height="64" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
  <circle cx="32" cy="32" r="30" fill="#28B95F"/>
  <path d="M20 32 L28 40 L44 24" stroke="white" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
</svg>
`

// Notification error icon
const notificationErrorSvg = `
<svg width="64" height="64" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
  <circle cx="32" cy="32" r="30" fill="#F04B69"/>
  <path d="M22 22 L42 42 M42 22 L22 42" stroke="white" stroke-width="4" stroke-linecap="round"/>
</svg>
`

// Notification info icon
const notificationInfoSvg = `
<svg width="64" height="64" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
  <circle cx="32" cy="32" r="30" fill="#0064FA"/>
  <circle cx="32" cy="20" r="4" fill="white"/>
  <rect x="28" y="28" width="8" height="20" rx="2" fill="white"/>
</svg>
`

async function generateIcons() {
  console.log('Generating icons...')

  // Generate main icon in various sizes
  const mainIconBuffer = Buffer.from(mainIconSvg)

  // PNG icons for different platforms
  const sizes = [16, 32, 48, 64, 128, 256, 512, 1024]
  for (const size of sizes) {
    await sharp(mainIconBuffer)
      .resize(size, size)
      .png()
      .toFile(path.join(ICONS_DIR, `${size}x${size}.png`))
    console.log(`  Created ${size}x${size}.png`)
  }

  // Main icon.png (512x512)
  await sharp(mainIconBuffer)
    .resize(512, 512)
    .png()
    .toFile(path.join(BUILD_DIR, 'icon.png'))
  console.log('  Created icon.png')

  // Tray icon (32x32)
  await sharp(Buffer.from(trayIconSvg))
    .resize(32, 32)
    .png()
    .toFile(path.join(BUILD_DIR, 'tray-icon.png'))
  console.log('  Created tray-icon.png')

  // Notification icons
  await sharp(Buffer.from(notificationSuccessSvg))
    .resize(64, 64)
    .png()
    .toFile(path.join(BUILD_DIR, 'notification-success.png'))
  console.log('  Created notification-success.png')

  await sharp(Buffer.from(notificationErrorSvg))
    .resize(64, 64)
    .png()
    .toFile(path.join(BUILD_DIR, 'notification-error.png'))
  console.log('  Created notification-error.png')

  await sharp(Buffer.from(notificationInfoSvg))
    .resize(64, 64)
    .png()
    .toFile(path.join(BUILD_DIR, 'notification-info.png'))
  console.log('  Created notification-info.png')

  // Windows ICO (requires multiple sizes embedded)
  // We'll use png2ico or electron-builder will handle it
  await sharp(mainIconBuffer)
    .resize(256, 256)
    .png()
    .toFile(path.join(BUILD_DIR, 'icon.ico.png'))
  console.log('  Created icon.ico.png (convert to .ico manually or let electron-builder handle it)')

  // macOS ICNS (electron-builder will generate from png)
  console.log('  macOS icns will be generated by electron-builder from icon.png')

  // Installer sidebar (164x314 for NSIS)
  const sidebarSvg = `
<svg width="164" height="314" viewBox="0 0 164 314" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="sidebarBg" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:#0064FA"/>
      <stop offset="100%" style="stop-color:#003D99"/>
    </linearGradient>
  </defs>
  <rect width="164" height="314" fill="url(#sidebarBg)"/>
  <g transform="translate(32, 100)">
    <path d="M20 20 L20 80 L60 80 L60 70 L30 70 L30 20 Z" fill="white"/>
    <rect x="65" y="60" width="30" height="20" rx="4" fill="#DCB40A"/>
  </g>
  <text x="82" y="200" text-anchor="middle" fill="white" font-family="Arial" font-size="14" font-weight="bold">CRM</text>
  <text x="82" y="220" text-anchor="middle" fill="white" font-family="Arial" font-size="12">Luelis</text>
</svg>
`

  await sharp(Buffer.from(sidebarSvg))
    .resize(164, 314)
    .png()
    .toFile(path.join(BUILD_DIR, 'installerSidebar.png'))
  console.log('  Created installerSidebar.png')

  // Note: Convert to BMP for NSIS manually or use imagemagick
  // convert installerSidebar.png installerSidebar.bmp

  console.log('\nDone! Icons generated in build/ directory.')
  console.log('\nNext steps:')
  console.log('1. Convert icon.ico.png to icon.ico (use https://convertico.com/ or imagemagick)')
  console.log('2. Convert installerSidebar.png to installerSidebar.bmp for NSIS')
  console.log('3. For macOS, electron-builder will generate icns from icon.png')
}

generateIcons().catch(console.error)
